### ISSUE TITLE
rake sneakers:run terminates without error messages

### ISSUE THREAD

**Issue by adisos** [jondot/sneakers#150]
My input:
`WORKERS=DispatchSnsHandler rake sneakers:run`

It shows:
```ruby
➜  wd git:(master) ✗ WORKERS=DispatchSnsHandler bin/rake sneakers:run
2015-08-19T09:02:32Z p-20579 t-3cwmg WARN: Loading runner configuration...
2015-08-19T09:02:32Z p-20579 t-3cwmg INFO: New configuration: #<Sneakers::Configuration:0x0000000904b7b8 @hash={:runner_config_file=>nil, :metrics=>nil, :daemonize=>false, :start_worker_delay=>0.2, :workers=>0, :log=>#<IO:<STDOUT>>, :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>3, :threads=>1, :durable=>true, :ack=>true, :heartbeat=>60, :exchange=>"muo", :exchange_type=>:direct, :hooks=>{}, :amqp=>"amqp://admin:asdasd@localhost:5672/newsletter", :vhost=>"newsletter", :handler=>Sneakers::Handlers::Oneshot, :logger=>#<Logger:0x0000000784d5a8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x0000000784d580 @datetime_format=nil>, @formatter=Sneakers::Support::ProductionFormatter, @logdev=#<Logger::LogDevice:0x0000000784d530 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x0000000784d508 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x0000000784d4b8>>>>, :worker_type=>"process", :worker_classes=>[DispatchSnsHandler]}>
2015-08-19T09:02:32Z p-20579 t-3cwmg WARN: Loading runner configuration...
2015-08-19T09:02:32Z p-20579 t-3cwmg INFO: New configuration: #<Sneakers::Configuration:0x00000008fab128 @hash={:runner_config_file=>nil, :metrics=>nil, :daemonize=>false, :start_worker_delay=>0.2, :workers=>0, :log=>#<IO:<STDOUT>>, :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>3, :threads=>1, :durable=>true, :ack=>true, :heartbeat=>60, :exchange=>"muo", :exchange_type=>:direct, :hooks=>{}, :amqp=>"amqp://admin:asdasd@localhost:5672/newsletter", :vhost=>"newsletter", :handler=>Sneakers::Handlers::Oneshot, :logger=>#<Logger:0x0000000784d5a8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x0000000784d580 @datetime_format=nil>, @formatter=Sneakers::Support::ProductionFormatter, @logdev=#<Logger::LogDevice:0x0000000784d530 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x0000000784d508 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x0000000784d4b8>>>>, :worker_type=>"process", :worker_classes=>[DispatchSnsHandler]}>
2015-08-19T09:02:32Z p-20579 t-3cwmg WARN: Loading runner configuration...
2015-08-19T09:02:32Z p-20579 t-3cwmg INFO: New configuration: #<Sneakers::Configuration:0x00000008fa6650 @hash={:runner_config_file=>nil, :metrics=>nil, :daemonize=>false, :start_worker_delay=>0.2, :workers=>0, :log=>#<IO:<STDOUT>>, :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>3, :threads=>1, :durable=>true, :ack=>true, :heartbeat=>60, :exchange=>"muo", :exchange_type=>:direct, :hooks=>{}, :amqp=>"amqp://admin:asdasd@localhost:5672/newsletter", :vhost=>"newsletter", :handler=>Sneakers::Handlers::Oneshot, :logger=>#<Logger:0x0000000784d5a8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x0000000784d580 @datetime_format=nil>, @formatter=Sneakers::Support::ProductionFormatter, @logdev=#<Logger::LogDevice:0x0000000784d530 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x0000000784d508 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x0000000784d4b8>>>>, :worker_type=>"process", :worker_classes=>[DispatchSnsHandler]}>
```
And quits. When I invoke this task in rails console - it's ok:
```ruby
2.1.5 :004 > ENV['WORKERS'] = 'DispatchSnsHandler'
 => "DispatchSnsHandler" 
2.1.5 :005 > Rake::Task['sneakers:run'].invoke
2015-08-19T09:05:15Z p-20687 t-913xo WARN: Loading runner configuration...
2015-08-19T09:05:15Z p-20687 t-913xo INFO: New configuration: #<Sneakers::Configuration:0x0000000868da28 @hash={:runner_config_file=>nil, :metrics=>nil, :daemonize=>false, :start_worker_delay=>0.2, :workers=>1, :log=>#<IO:<STDOUT>>, :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>3, :threads=>1, :durable=>true, :ack=>true, :heartbeat=>60, :exchange=>"muo", :exchange_type=>:direct, :hooks=>{}, :amqp=>"amqp://admin:asdasd@localhost:5672/newsletter", :vhost=>"newsletter", :handler=>Sneakers::Handlers::Oneshot, :logger=>#<Logger:0x00000008be8d88 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x00000008be8ce8 @datetime_format=nil>, @formatter=Sneakers::Support::ProductionFormatter, @logdev=#<Logger::LogDevice:0x00000008be8c70 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00000008be8bd0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000008be8b30>>>>, :worker_type=>"process", :worker_classes=>[DispatchSnsHandler]}>
2015-08-19T09:05:15Z p-20687 t-913xo WARN: Loading runner configuration...
2015-08-19T09:05:15Z p-20687 t-913xo INFO: New configuration: #<Sneakers::Configuration:0x0000000856f6a0 @hash={:runner_config_file=>nil, :metrics=>nil, :daemonize=>false, :start_worker_delay=>0.2, :workers=>1, :log=>#<IO:<STDOUT>>, :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>3, :threads=>1, :durable=>true, :ack=>true, :heartbeat=>60, :exchange=>"muo", :exchange_type=>:direct, :hooks=>{}, :amqp=>"amqp://admin:asdasd@localhost:5672/newsletter", :vhost=>"newsletter", :handler=>Sneakers::Handlers::Oneshot, :logger=>#<Logger:0x00000008be8d88 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x00000008be8ce8 @datetime_format=nil>, @formatter=Sneakers::Support::ProductionFormatter, @logdev=#<Logger::LogDevice:0x00000008be8c70 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00000008be8bd0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000008be8b30>>>>, :worker_type=>"process", :worker_classes=>[DispatchSnsHandler]}>
2015-08-19T09:05:15Z p-20687 t-913xo WARN: Loading runner configuration...
2015-08-19T09:05:15Z p-20687 t-913xo INFO: New configuration: #<Sneakers::Configuration:0x0000000857e3a8 @hash={:runner_config_file=>nil, :metrics=>nil, :daemonize=>false, :start_worker_delay=>0.2, :workers=>1, :log=>#<IO:<STDOUT>>, :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>3, :threads=>1, :durable=>true, :ack=>true, :heartbeat=>60, :exchange=>"muo", :exchange_type=>:direct, :hooks=>{}, :amqp=>"amqp://admin:asdasd@localhost:5672/newsletter", :vhost=>"newsletter", :handler=>Sneakers::Handlers::Oneshot, :logger=>#<Logger:0x00000008be8d88 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x00000008be8ce8 @datetime_format=nil>, @formatter=Sneakers::Support::ProductionFormatter, @logdev=#<Logger::LogDevice:0x00000008be8c70 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00000008be8bd0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000008be8b30>>>>, :worker_type=>"process", :worker_classes=>[DispatchSnsHandler]}>
2015-08-19T09:05:15Z p-20702 t-913xo DEBUG: [worker-mailer.dispatch.sns_responses:1:kci6rd][#<Thread:0x00000001cee658>][mailer.dispatch.sns_responses][#<Sneakers::Configuration:0x0000000854b048>] New worker: subscribing.
2015-08-19T09:05:15Z p-20702 t-913xo DEBUG: Sent protocol preamble
2015-08-19T09:05:15Z p-20702 t-913xo DEBUG: Sent connection.start-ok
2015-08-19T09:05:15Z p-20702 t-913xo DEBUG: Heartbeat interval negotiation: client = 60, server = 580, result = 60
2015-08-19T09:05:15Z p-20702 t-913xo INFO: Heartbeat interval used (in seconds): 60
2015-08-19T09:05:15Z p-20702 t-913xo DEBUG: Sent connection.tune-ok with heartbeat interval = 60, frame_max = 131072, channel_max = 65535
2015-08-19T09:05:15Z p-20702 t-913xo DEBUG: Sent connection.open with vhost = newsletter
2015-08-19T09:05:15Z p-20702 t-913xo DEBUG: Initializing heartbeat sender...
```

**Comment by adisos** [comment]
I think problem is here: https://github.com/jondot/sneakers/blob/8ea38a287e6fc7511fb53564d6ddf567dfc88d37/lib/sneakers/tasks.rb#L16

Because, now I reworked to this style:
```ruby
r = Sneakers::Runner.new(ENV.fetch('WORKERS', '').split(',').map { |w| w.constantize })
```
and it works.

**Comment by RmMsr** [comment]
We seem to have the same error. Log says:

```
Unexpected error wrong number of arguments (2 for 0)
  /.../app/workers/some_worker.rb:12:in `initialize'
  /.../ruby/2.2.0/bundler/gems/sneakers-8ea38a287e6f/lib/sneakers/workergroup.rb:26:in `new'
  /.../ruby/2.2.0/bundler/gems/sneakers-8ea38a287e6f/lib/sneakers/workergroup.rb:26:in `block in run'
  /.../ruby/2.2.0/bundler/gems/sneakers-8ea38a287e6f/lib/sneakers/workergroup.rb:26:in `map'
  /.../ruby/2.2.0/bundler/gems/sneakers-8ea38a287e6f/lib/sneakers/workergroup.rb:26:in `run'
```
