### ISSUE TITLE
Unstable integration spec (seed 24399)

### ISSUE THREAD

**Issue by rud** [jondot/sneakers#179]
Seen at https://travis-ci.org/jondot/sneakers/jobs/84462968
```
10.02s$ bundle exec rake
Run options: --seed 24399
# Running:
...................................starting workers.
waiting for workers to stabilize (5s).
publishing...
E................................................................
Finished in 7.070938s, 14.1424 runs/s, 14.2838 assertions/s.
  1) Error:
integration::first#test_0001_should pull down 100 jobs from a real queue:
NoMethodError: undefined method `start' for #<Object:0x00000002460378>
    /home/travis/build/jondot/sneakers/lib/sneakers/publisher.rb:27:in `ensure_connection!'
    /home/travis/build/jondot/sneakers/lib/sneakers/publisher.rb:10:in `block in publish'
    /home/travis/build/jondot/sneakers/lib/sneakers/publisher.rb:9:in `synchronize'
    /home/travis/build/jondot/sneakers/lib/sneakers/publisher.rb:9:in `publish'
    /home/travis/build/jondot/sneakers/spec/sneakers/integration_spec.rb:93:in `block (4 levels) in <top (required)>'
    /home/travis/build/jondot/sneakers/spec/sneakers/integration_spec.rb:92:in `times'
    /home/travis/build/jondot/sneakers/spec/sneakers/integration_spec.rb:92:in `block (3 levels) in <top (required)>'
```

I can consistently reproduce this locally by running (I have RabbitMQ installed):
```
INTEGRATION_LOG=1 INTEGRATION=1 SEED=24399 rake
```

I tried to get the gem 'minitest-bisect' to help figure out the minimal number of files to run to setup for this failure, but did not manage to get it to work. It seems a bit fickle and not very communicative.

Anyway, I think there's a mock setup elsewhere that is leaking between tests.  Any help on fixing this is much appreciated.

**Comment by rud** [comment]
Sorry for the noise, fixed in 81ca8d0.
