### ISSUE TITLE
Unexpected error Trying to send frame through a closed connection

### ISSUE THREAD

**Issue by veetow** [jondot/sneakers#196]
Hi all,

I'm hitting an issue intermittently where my workers try to cancel a consumer on an already closed channel:

```
2016-01-07_19:23:19.41261 Unexpected error Trying to send frame through a closed connection. Frame is #<AMQ::Protocol::MethodFrame:0x00000003500db8 @payload="\x00<\x00\x1E bunny-1449600596000-554490885194\x00", @channel=1>, method class is AMQ::Protocol::Basic::Cancel
2016-01-07_19:23:19.41261   /srv/workers/vendor/bundle/ruby/2.1.0/gems/bunny-2.2.1/lib/bunny/session.rb:918:in `send_frame'
2016-01-07_19:23:19.41261   /srv/workers/vendor/bundle/ruby/2.1.0/gems/bunny-2.2.1/lib/bunny/channel.rb:968:in `basic_cancel'
2016-01-07_19:23:19.41262   /srv/workers/vendor/bundle/ruby/2.1.0/gems/bunny-2.2.1/lib/bunny/consumer.rb:84:in `cancel'
2016-01-07_19:23:19.41262   /srv/workers/vendor/bundle/ruby/2.1.0/gems/sneakers-2.3.5/lib/sneakers/queue.rb:60:in `unsubscribe'
2016-01-07_19:23:19.41262   /srv/workers/vendor/bundle/ruby/2.1.0/gems/sneakers-2.3.5/lib/sneakers/worker.rb:96:in `stop'
2016-01-07_19:23:19.41262   /srv/workers/vendor/bundle/ruby/2.1.0/gems/sneakers-2.3.5/lib/sneakers/workergroup.rb:44:in `block in stop'
2016-01-07_19:23:19.41263   /srv/workers/vendor/bundle/ruby/2.1.0/gems/sneakers-2.3.5/lib/sneakers/workergroup.rb:43:in `each'
2016-01-07_19:23:19.41263   /srv/workers/vendor/bundle/ruby/2.1.0/gems/sneakers-2.3.5/lib/sneakers/workergroup.rb:43:in `stop'
2016-01-07_19:23:19.41263   /srv/workers/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/worker.rb:57:in `block (2 levels) in install_signal_handlers'
2016-01-07_19:23:19.41263   /srv/workers/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/signal_thread.rb:98:in `call'
2016-01-07_19:23:19.41263   /srv/workers/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/signal_thread.rb:98:in `main'
```

I'm still not sure what the root cause is, but it seems like sneakers could handle this a little more gracefully but checking if the channel is open (maybe bunny is in the process of reconnecting?).  Or, at the very least, maybe the workers should get killed and respawned?  As it stands now, I have to manually restart the workers by killing and restarting the process.

**Comment by veetow** [comment]
https://github.com/ruby-amqp/bunny/blob/9817b2fae1bfa621457e40d17ede55c368838a6b/lib/bunny/exceptions.rb#L89

**Comment by michaelklishin** [comment]
Connection failures cannot be entirely avoided and automatic connection recovery in Bunny does not cover them for outgoing messages. Ultimately publisher confirms is what publishers should use.
