### ISSUE TITLE
Problems with "How to: running a stand alone worker" example

### ISSUE THREAD

**Issue by lbrito1** [jondot/sneakers#198]
By following the steps exactly as described in [How to: running a stand alone worker](https://github.com/jondot/sneakers/wiki/How-to:-running-a-stand-alone-worker), I'm having a few issues.

First, there are some `require`s that seem to be missing, namely:

    require 'sneakers'
    require 'sneakers/metrics/statsd_metrics'

Without those requires, I get `uninitialized constant Sneakers::Metrics` and `undefined method 'configure' for Sneakers:Module` errors when running `foreman start`. Since I'm new to Sneakers I preferred to open an issue first rather than simply editing the wiki.

After those modifications, I still get the following error when running foreman:

    $ foreman start
    14:19:29 myworker.1 | started with pid 6152
    14:19:29 myworker.1 | 2016-01-18T17:19:29Z p-6152 t-ovl0dc9w8 WARN: Loading runner configuration...
    14:19:29 myworker.1 | /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/configuration.rb:94:in `inspect_with_redaction': undefined method `sub' for nil:NilClass (NoMethodError)
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/runner.rb:62:in `reload_config!'
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/runner.rb:11:in `block in run'
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine/config_loader.rb:39:in `reload_config'
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine/config_loader.rb:32:in `initialize'
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine/daemon.rb:29:in `initialize'
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine.rb:51:in `new'
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine.rb:51:in `create'
    14:19:29 myworker.1 | 	from /Users/leonardobrito/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/runner.rb:11:in `run'
    14:19:29 myworker.1 | 	from bin/myworker.rb:19:in `<main>'
    14:19:29 myworker.1 | exited with code 1
    14:19:29 system     | sending SIGTERM to all processes

Other than the two mentioned requires, all the rest is exactly the same from what is indicated in the how-to (except that I added the extension to bin/myworker.rb in the Procfile). 

Are there any additional steps I'm supposed to do before trying to run this example? I'm guessing something needs to be filled in the Myworker model (lib/myworker.rb).

**Comment by StasKoval** [comment]
You need define ENV['AMQP_URL'] .
