### ISSUE TITLE
AMQ::Protocol::EmptyResponseError: Empty response received from the server.

### ISSUE THREAD

**Issue by kanmaniselvan** [jondot/sneakers#238]
In Production, two workers are running and they process messages from four different queues. I'm constantly getting this error in **one of the workers**. And the error is getting repeated only for **a particular queue**. Rest of the queues are working normal.

**Error Log:**
```
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: Got an exception when receiving data: Connection reset by peer (Errno::ECONNRESET)
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: Exception in the reader loop: AMQ::Protocol::EmptyResponseError: Empty response received from the server.
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: Backtrace: 
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: 	/home/deploy/websites/production/shared/bundle/ruby/2.3.0/gems/amq-protocol-2.0.1/lib/amq/protocol/frame.rb:60:in `decode_header'
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: 	/home/deploy/websites/production/shared/bundle/ruby/2.3.0/gems/bunny-2.2.2/lib/bunny/transport.rb:245:in `read_next_frame'
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: 	/home/deploy/websites/production/shared/bundle/ruby/2.3.0/gems/bunny-2.2.2/lib/bunny/reader_loop.rb:68:in `run_once'
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: 	/home/deploy/websites/production/shared/bundle/ruby/2.3.0/gems/bunny-2.2.2/lib/bunny/reader_loop.rb:35:in `block in run_loop'
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: 	/home/deploy/websites/production/shared/bundle/ruby/2.3.0/gems/bunny-2.2.2/lib/bunny/reader_loop.rb:32:in `loop'
2016-08-04T05:49:00Z p-31012 t-k4wz4 ERROR: 	/home/deploy/websites/production/shared/bundle/ruby/2.3.0/gems/bunny-2.2.2/lib/bunny/reader_loop.rb:32:in `run_loop'
2016-08-04T05:49:04Z p-31012 t-qvnfk WARN: Retrying connection on next host in line: 192.168.22.13:5672
2016-08-04T05:49:04Z p-31012 t-qcazw WARN: Retrying connection on next host in line: 192.168.22.13:5672
2016-08-04T05:49:04Z p-31012 t-qcazw INFO: Heartbeat interval used (in seconds): 2
2016-08-04T05:49:04Z p-31012 t-qvnfk INFO: Heartbeat interval used (in seconds): 2
```

**Sneakers Config file**
```
require 'sneakers'
require 'sneakers/handlers/maxretry'

num_workers = 2
num_threads = 5
num_prefetch = 5

Sneakers.configure( :amqp => ENV['RABBITMQ_URL'], handler: Sneakers::Handlers::Maxretry, daemonize: !Rails.env.development?,
                    pid_path: 'tmp/pids/sneakers.pid', log: 'log/sneakers.log',
                    :timeout_job_after => 30, :workers => num_workers, :threads => num_threads, :prefetch => num_prefetch )
Sneakers.logger.level = Logger::INFO 
```
**Gemfile.lock**
```
    sneakers (2.3.5)
      bunny (~> 2.2.0)
```

**RabbitMQ Version:** 3.6.4

**Log file:** [sneakers.txt](https://github.com/jondot/sneakers/files/401469/sneakers.txt)

**Comment by michaelklishin** [comment]
`Connection reset by peer (Errno::ECONNRESET)` is fairly self-explanatory: RabbitMQ or an intermediary (e.g. a proxy) closed TCP connection. See server logs for possible clues.

**Comment by kanmaniselvan** [comment]
Actually one of the worker stopped working, but the other **one continued to work**. 
And also, why did the worker hang and not recover at all?

 Is there any relation between workers and queues? Why isn't the one functioning worker processing all queues?

And which server server logs should be checked for clues?

I'm attaching the RabbitMQ log file [rabbitmq.txt](https://github.com/jondot/sneakers/files/401795/rabbitmq.txt). It says, `client unexpectedly closed TCP connection`

**Comment by kanmaniselvan** [comment]
Increasing the RAM of the server fixed this issue.

**Comment by michaelklishin** [comment]
There are only two server logs (and in future releases starting with 3.7.0, it will be just one).

**Comment by michaelklishin** [comment]
This likely means your publishing connections were blocked by an alarm.
