### ISSUE TITLE
Local configuration occurred error

### ISSUE THREAD

**Issue by thinhhuynh** [jondot/sneakers#246]
when i configured in local as
`app/job/mailer_job.rb`

``` ruby
class MailerJob
  include Sneakers::Worker
  from_queue "q.mailer",
             durable: true,
             env: :development,
             ack: true,
             exchange: 'mailer',
             exchange_type: :fanout,
             heartbeat: 2

  def work(raw_post)   
    puts "****************************************************************************"
    puts "MailerJob First: #{raw_post}"
    ack! # we need to let queue know that message was received
  end
end
```

After I ran the command `WORKER=MailerWorker rake sneakers:run` The errors were as 

```
rake aborted!
NoMethodError: private method `warn' called for nil:NilClass
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/runner.rb:43:in `reload_config!'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/runner.rb:11:in `block in run'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine/config_loader.rb:39:in `reload_config'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine/config_loader.rb:32:in `initialize'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine/daemon.rb:29:in `initialize'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine.rb:51:in `new'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/serverengine-1.5.11/lib/serverengine.rb:51:in `create'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/runner.rb:11:in `run'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/sneakers-2.3.5/lib/sneakers/tasks.rb:42:in `block (2 levels) in <top (required)>'
/home/hdthinh/.rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/hdthinh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/hdthinh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => sneakers:run
```

P/S:
This worker worked well with global configuration

``` ruby
Sneakers.configure :heartbeat => 2,
                   :amqp => 'amqp://guest:guest@127.0.0.1:5672',
                   :vhost => '/',
                   :exchange => 'mailer',
                   :exchange_type => :fanout, #direct
                   :durable => true,
                   :log => 'sneakers.mailer.log'

Sneakers.logger.level = Logger::INFO # the default DEBUG is too noisy
```

**Comment by michaelklishin** [comment]
Looks like a logger is not initialized in this case.

**Comment by michaelklishin** [comment]
On an unrelated note, using a heartbeat timeout of 2 seconds runs a high risk of false positives. Consider bumping it to 5-6 seconds.

**Comment by thinhhuynh** [comment]
@michaelklishin, How can I initialize logger in local configuration?
Thanks!

**Comment by samacs** [comment]
@thinhhuynh did you find how to initialize the logger?

**Comment by michaelklishin** [comment]
This specific issue was a bug which I cannot find a.t.m. In master it is possible to pass in any `Bunny::Session` instead you please, including with a custom-configured logger.
