### ISSUE TITLE
Handle Bunny::Session continuation_timeout cleanly

### ISSUE THREAD

**Issue by veetow** [jondot/sneakers#262]
# Versions
    bunny (2.6.1)
    sneakers (2.4.0)
    serverengine (1.5.11)

# Overview
I often see this in my workers when my development RabbitMQ cluster is overloaded or otherwise having issues.  It would be nice if Sneakers exposed a clean way to handle this in place of the current behavior.

# Traceback

```
Unexpected error Timeout::Error
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/bunny-2.6.1/lib/bunny/concurrent/continuation_queue.rb:33:in `block in poll'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/bunny-2.6.1/lib/bunny/concurrent/continuation_queue.rb:30:in `synchronize'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/bunny-2.6.1/lib/bunny/concurrent/continuation_queue.rb:30:in `poll'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/bunny-2.6.1/lib/bunny/channel.rb:1757:in `wait_on_continuations'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/bunny-2.6.1/lib/bunny/channel.rb:639:in `block in basic_qos'
  /opt/ruby/embedded/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
  /opt/ruby/embedded/lib/ruby/2.1.0/timeout.rb:101:in `call'
  /opt/ruby/embedded/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/bunny-2.6.1/lib/bunny/channel.rb:638:in `basic_qos'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/sneakers-2.4.0/lib/sneakers/queue.rb:26:in `subscribe'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/sneakers-2.4.0/lib/sneakers/worker.rb:105:in `run'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/sneakers-2.4.0/lib/sneakers/workergroup.rb:36:in `block in run'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/sneakers-2.4.0/lib/sneakers/workergroup.rb:35:in `each'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/sneakers-2.4.0/lib/sneakers/workergroup.rb:35:in `run'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/worker.rb:74:in `main'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_process_server.rb:79:in `block in start_worker'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/process_manager.rb:107:in `call'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/process_manager.rb:107:in `block in fork'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/process_manager.rb:99:in `fork'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/process_manager.rb:99:in `fork'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_process_server.rb:69:in `start_worker'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_worker_server.rb:132:in `delayed_start_worker'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_worker_server.rb:105:in `block in keepalive_workers'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_worker_server.rb:97:in `each'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_worker_server.rb:97:in `each_with_index'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_worker_server.rb:97:in `keepalive_workers'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_worker_server.rb:54:in `run'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/multi_process_server.rb:40:in `run'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/server.rb:88:in `main'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/daemon.rb:101:in `main'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/serverengine-1.5.11/lib/serverengine/daemon.rb:90:in `run'
  /opt/poe/vendor/bundle/ruby/2.1.0/gems/sneakers-2.4.0/lib/sneakers/runner.rb:12:in `run'
  /opt/poe/lib/poe/service.rb:45:in `run_sneakers'
  /opt/poe/lib/poe/service.rb:41:in `run'
  ./bin/service:8:in `<main>'
```

**Comment by semantic-lee** [comment]
same :scream:

**Comment by c0mrade** [comment]
@veetow @semantic-lee is there a way to increase a timeout in sneakers?

**Comment by gabrieljoelc** [comment]
> is there a way to increase a timeout in sneakers?

@c0mrade please see [Configuration wiki](https://github.com/jondot/sneakers/wiki/Configuration)

**Comment by michaelklishin** [comment]
`Sneakers::Queue` accepts a `:connection` key that allow you configure a Bunny connection however you want (including continuation timeouts).
