### ISSUE TITLE
Got `deadlock, recursive locking` On High Volume Queue

### ISSUE THREAD

**Issue by edwinlunando** [jondot/sneakers#263]
Hi, this might not be a bug. In production while consuming a lot of message(30K-ish), the sneakers worker start getting this error.
```
[#<Sneakers::Configuration:0x005651cd918be0>] unexpected error [Exception error="deadlock; recursive locking" error_class=ThreadError backtrace=/usr/local/lib/ruby/2.3.0/monitor.rb:187:in `lock',/usr/local/lib/ruby/2.3.0/monitor.rb:187:in `mon_enter',/usr/local/lib/ruby/2.3.0/monitor.rb:212:in `mon_synchronize',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:91:in `connection',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:319:in `block in save',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:334:in `rollback_active_record_state!',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:318:in `save',/usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:41:in `save',/app/app/workers/notif_worker.rb:17:in `work',/usr/local/bundle/gems/sneakers-2.3.5/lib/sneakers/worker.rb:58:in `block (3 levels) in do_work',/usr/local/bundle/gems/sneakers-2.3.5/lib/sneakers/metrics/null_metrics.rb:8:in `timing',/usr/local/bundle/gems/sneakers-2.3.5/lib/sneakers/worker.rb:54:in `block (2 levels) in do_work',/usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout',/usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout',/usr/local/bundle/gems/sneakers-2.3.5/lib/sneakers/worker.rb:53:in `block in do_work',/usr/local/bundle/gems/thread-0.1.7/lib/thread/pool.rb:56:in `execute',/usr/local/bundle/gems/thread-0.1.7/lib/thread/pool.rb:404:in `block (2 levels) in spawn_thread',/usr/local/bundle/gems/thread-0.1.7/lib/thread/pool.rb:371:in `loop',/usr/local/bundle/gems/thread-0.1.7/lib/thread/pool.rb:371:in `block in spawn_thread']
2017-01-04T08:00:42Z p-153 t-gsbwf2zxs ERROR: [worker-notif.container:1:ezlk86][#<Thread:0x005624b8d782e0>][notif.container][#<Sneakers:
```
If I publish the message one by one, it works normally. This is my `sneakers.rb`.
```
# config/initializers/sneakers.rb
require 'sneakers/handlers/maxretry'
Sneakers.configure  :amqp => "#{ENV['AMQP_URL']}",
                    :vhost => "#{ENV['AMQP_VHOST']}",
                    :exchange_type => :direct,

                    :runner_config_file => nil,  # A configuration file (see below)
                    :metrics => nil,             # A metrics provider implementation
                    :daemonize => false,         # Send to background
                    :workers => 2,               # Number of per-cpu processes to run
                    :log  => 'sneakers.log',     # Log file
                    :pid_path => 'sneakers.pid', # Pid file

                    :timeout_job_after => 5,      # Maximal seconds to wait for job
                    :prefetch => 10,              # Grab 10 jobs together. Better speed.
                    :threads => 10,               # Threadpool size (good to match prefetch)
                    :env => ENV['RAILS_ENV'],      # Environment
                    :durable => true,             # Is queue durable?
                    :ack => true,                 # Must we acknowledge?
                    :heartbeat => 2,              # Keep a good connection with broker
                    :exchange => 'notif',      # AMQP exchange
                    :hooks => {},                 # prefork/postfork hooks
                    :start_worker_delay => 10,    # Delay between thread startup

                    :handler => Sneakers::Handlers::Maxretry,          # Change handler to Maxretry, default is Oneshot
                    retry_timeout:      60 * 1000  #60 sec

Sneakers.logger.level = Logger::INFO
```

I thought this is related to the number of workers and threads. In my configuration is 2 workers and 10 threads, it means, there are 20 threads that connect to the database, right? And, what is `prefetch` means? Is there any solution to my error? Thank you.

**Comment by michaelklishin** [comment]
Sneakers or Bunny do not implement mutexes, Ruby standard library does. Ruby has two mutex implementations: a non-reentrant `Mutex` and a somewhat less efficient (5-10%) but reentrant `Monitor`. Bunny lets you choose either.
