### ISSUE TITLE
Windows 10: Unexpected error unsupported signal SIGQUIT

### ISSUE THREAD

**Issue by adback03** [jondot/sneakers#287]
When trying to run my worker on Windows 10, I am receiving the following error:

```
Unexpected error unsupported signal SIGQUIT
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/signal_thread.rb:46:in `trap'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/signal_thread.rb:46:in `trap'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/server.rb:69:in `block in install_sign
andlers'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/signal_thread.rb:31:in `initialize'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/server.rb:67:in `new'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/server.rb:67:in `install_signal_handle
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/daemon.rb:100:in `main'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/serverengine-1.5.11/lib/serverengine/daemon.rb:90:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sneakers-2.5.0/lib/sneakers/runner.rb:12:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sneakers-2.5.0/lib/sneakers/tasks.rb:42:in `block (2 levels) in <top (requi
>'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
  C:/Ruby23-x64/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
  C:/Ruby23-x64/bin/rake:22:in `load'
  C:/Ruby23-x64/bin/rake:22:in `<main>'
```

Here is the worker:

```ruby
require 'sneakers'
require 'sneakers/runner'

class TestWorker
  include Sneakers::Worker
  from_queue 'test_queue',
             :amqp => 'amqp://guest:guest@localhost:5672',
             :durable => true,
             :auto_delete => false,
             :ack => true,
             :threads => 50,
             :prefetch => 50,
             :timeout_job_after => 1,
             :exchange => 'test',
             :heartbeat => 5

  def work(msg)
    logger.info "MESSAGE RECEIVED #{msg}"
    ack!
  end
end
```

I have had this exact worker run just fine on Ubuntu 14.04, but seems to be struggling on Windows 10. Any ideas? Thanks!

Issue cross referenced here: https://github.com/treasure-data/serverengine/issues/89

**Comment by michaelklishin** [comment]
Windows [does not support the same set of signals as Linux](https://stackoverflow.com/questions/18281008/what-do-with-sigquit-signal-when-porting-to-mingw). I'm not sure why you are asking Sneakers maintainers about an OS-specific issue in Server Engine.
