### ISSUE TITLE
Broken pipe - SSL_connect

### ISSUE THREAD

**Issue by rept** [jondot/sneakers#389]
Hi,

I use Sneakers for a background processing (ActiveJob).

Mostly it's working beautifully.  However today I ran into something.  When I looked in sneakers.log I found an error message: 'Broken pipe - SSL_connect'.

It's given a SSL_connect problem but shouldn't Sneakers handle this gracefully and retry to setup the connection.  I tried several times over a timespan but always got this error.  Until I killed the workers.  The workers were automatically restarted by eye, and after this all was fine.

This is the stacktrace:

```
2019-03-28T16:08:48Z p-10450 t-143zzc ERROR: [Exception error="Broken pipe - SSL_connect" error_class=Errno::EPIPE worker_class=EscalationEventWorker 
backtrace=/prod/shared/bundle/ruby/2.6.0/gems/bunny-2.13.0/lib/bunny/transport.rb:86:in `connect',/prod/shared/bundle/ruby/2.6.0/gems/bunny-2.13.0/lib/bunny/transport.rb:86:in `connect',/prod/shared/bundle/ruby/2.6.0/gems/bunny-2.13.0/lib/bunny/session.rb:312:in `start',/prod/shared/bundle/ruby/2.6.0/gems/sneakers-2.11.0/lib/sneakers/publisher.rb:31:in `connect!',/prod/shared/bundle/ruby/2.6.0/gems/sneakers-2.11.0/lib/sneakers/publisher.rb:24:in `block in ensure_connection!',/prod/shared/bundle/ruby/2.6.0/gems/sneakers-2.11.0/lib/sneakers/publisher.rb:23:in `synchronize',/prod/shared/bundle/ruby/2.6.0/gems/sneakers-2.11.0/lib/sneakers/publisher.rb:23:in `ensure_connection!',/prod/shared/bundle/ruby/2.6.0/gems/sneakers-2.11.0/lib/sneakers/publisher.rb:15:in `publish',/prod/shared/bundle/ruby/2.6.0/gems/sneakers-2.11.0/lib/sneakers/worker.rb:138:in `enqueue',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/queue_adapters/sneakers_adapter.rb:28:in `block in enqueue',/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/queue_adapters/sneakers_adapter.rb:26:in `enqueue',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/enqueuing.rb:53:in `block in enqueue',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks',/prod/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/instrumentation/active_job.rb:61:in `block in run_in_trace',/prod/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/method_tracer.rb:74:in `block in trace_execution_scoped',/prod/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped',/prod/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/method_tracer.rb:72:in `trace_execution_scoped',/prod/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/instrumentation/active_job.rb:60:in `run_in_trace',/prod/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/instrumentation/active_job.rb:38:in `enqueue',/prod/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-6.2.0.354/lib/new_relic/agent/instrumentation/active_job.rb:19:in `block (4 levels) in <main>',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `instance_exec',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/logging.rb:17:in `block (3 levels) in <module:Logging>',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/logging.rb:46:in `block in tag_logger',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/logging.rb:46:in `tag_logger',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/logging.rb:16:in `block (2 levels) in <module:Logging>',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `instance_exec',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks',/prod/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/enqueuing.rb:49:in `enqueue',/prod/shared/bundle/ruby/2.6.0/gems/activejob-5.2.1/lib/active_job/enqueuing.rb:20:in `perform_later'`
```

**Comment by michaelklishin** [comment]
There isn't much detail to work with but generally speaking Bunny doesn't retry initial connections, only upon connection failures. When initial connection attemptes fail, it should be more visible and strongly suggests a misconfiguration or a scenario where e.g. certificates change or expire. Retrying will not yield anything in those cases
