### ISSUE TITLE
Error with nil logger

### ISSUE THREAD

**Issue by molfar** [jondot/sneakers#395]
I set up sneakers with rails project. Everything following instructions. But have this error:

```
Unexpected error undefined method `debug' for nil:NilClass
Did you mean?  debugger
  /Users/molfar/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sneakers-2.11.0/lib/sneakers/worker.rb:114:in `worker_trace'
  /Users/molfar/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sneakers-2.11.0/lib/sneakers/worker.rb:103:in `run'
  /Users/molfar/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sneakers-2.11.0/lib/sneakers/workergroup.rb:42:in `block in run'
  /Users/molfar/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sneakers-2.11.0/lib/sneakers/workergroup.rb:41:in `each'
  /Users/molfar/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sneakers-2.11.0/lib/sneakers/workergroup.rb:41:in `run'
```

**Comment by michaelklishin** [comment]
This project is not tied to Rails. We should make the logging method more defensive. You are welcome to contribute a PR.

**Comment by shime** [comment]
I've managed to work around this problem (with Rails 6.0.0) by explicitly setting the logger.

```ruby
Sneakers.logger = Rails.logger
Sneakers::Worker.logger = Rails.logger
```
