### ISSUE TITLE
"Could not obtain a database connection" and other concurrency errors

### ISSUE THREAD

**Issue by abevoelker** [jondot/sneakers#42]
I am having a lot of database timeout errors, which tend to occur in groups like this:

```
2014-04-14T00:42:40Z p-29936 t-owd74tqb4 ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29936 t-owd74tk38 ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29936 t-owd74tqms ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29936 t-owd74tk74 ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29936 t-owd74tqiw ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29936 t-owd74u3pc ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29967 t-owd74tk5g ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29967 t-owd74tra4 ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
2014-04-14T00:42:40Z p-29967 t-owd74tqyg ERROR: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
```

This is after setting `pool: 15` in database.yml and setting both `:prefetch => 15` and `:threads => 15` in my sneakers initializer (`config/initializers/sneakers.rb`).  I have my Postgres database configured to accept 300 connections and the sneakers rake task is the only thing running against it.  This is running on an Intel i5 CPU which presents 4 cores to the OS, so between that and the default `:workers` value in lib/sneakers.rb I expect it's starting 4 processes.  When I change these thread variables to 25, the errors seem less frequent, but I still see them.  I read the [Auto-scaling section](https://github.com/jondot/sneakers/wiki/Auto-scaling#how-to-tune-resources) in the wiki and I'm not sure why this should happen if the pool size == the sneakers thread size.

Here are some other errors I'm seeing that seem concurrency-related (sorry for the weird linebreaks, copied+pasted from my console):

```
2014-04-14T01:23:50Z p-21926 t-orivh32jo ERROR: deadlock; recursive locking
2014-04-14T01:23:50Z p-21926 t-orivh32jo ERROR: deadlock; recursive locking
2014-04-14T01:23:50Z p-21926 t-orivh32jo ERROR: deadlock; recursive locking
2014-04-14T01:23:50Z p-21926 t-orivh0fmg ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh1b88 ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh1bvk ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh26sc ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh0sh8 ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh32jo ERROR: deadlock; recursive locking
2014-04-14T01:23:50Z p-21926 t-orivh26w8 ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh0s1o ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh1bg0 ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh32vc ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh0sl4 ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh0lzw ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh26kk ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh0ssw ERROR: Attempt to unlock a mutex which is locked by another thread
2014-04-14T01:23:50Z p-21926 t-orivh32jo ERROR: deadlock; recursive locking
2014-04-14T01:23:50Z p-21926 t-orivh32jo ERROR: deadlock; recursive locking
2014-04-14T01:23:50Z p-21926 t-orivh32jo ERROR: deadlock; recursive locking
```

```
2014-04-14T01:23:36Z p-21967 t-oriv4a1l4 ERROR: PG::DuplicatePstatement: ERROR:  prepared statement "a9" already exists
```

```
2014-04-14T01:23:41Z p-21967 t-orivh3ybk ERROR: timeout
E, [2014-04-14T01:23:41.352062 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>: Exc
eption in the reader loop: IOError: closed stream
E, [2014-04-14T01:23:41.393205 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>: Bac
ktrace: 
E, [2014-04-14T01:23:41.393251 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/cruby/socket.rb:48:in `select'
E, [2014-04-14T01:23:41.393272 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/cruby/socket.rb:48:in `rescue in
 read_fully'
E, [2014-04-14T01:23:41.393305 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/cruby/socket.rb:39:in `read_full
y'
E, [2014-04-14T01:23:41.393323 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/transport.rb:200:in `read_next_f
rame'
E, [2014-04-14T01:23:41.393340 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:63:in `run_once'
E, [2014-04-14T01:23:41.393356 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:33:in `block in r
un_loop'
E, [2014-04-14T01:23:41.393372 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:30:in `loop'
E, [2014-04-14T01:23:41.393390 #21957] ERROR -- #<Bunny::Session:69863549381840 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:30:in `run_loop'
2014-04-14T01:23:41Z p-21967 t-orivh1bvk ERROR: timeout
E, [2014-04-14T01:23:41.537716 #21957] ERROR -- #<Bunny::Session:69863550593340 foo@10.0.3.6:5672, vhost=/>: Exc
eption in the reader loop: IOError: stream closed
2014-04-14T01:23:41Z p-21967 t-orivh0s1o ERROR: timeout
2014-04-14T01:23:41Z p-21957 t-orivh0m3s ERROR: timeout
E, [2014-04-14T01:23:41.340814
 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>: Exception in the reader loop: Err
no::ECONNRESET: Connection reset by peer
E, [2014-04-14T01:23:42.028937 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>: Bac
ktrace: 
E, [2014-04-14T01:23:42.028967 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/cruby/socket.rb:41:in `read_nonb
lock'
E, [2014-04-14T01:23:42.028991 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/cruby/socket.rb:41:in `block in 
read_fully'
E, [2014-04-14T01:23:42.029014 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/cruby/socket.rb:40:in `loop'
E, [2014-04-14T01:23:42.029035 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/cruby/socket.rb:40:in `read_full
y'
E, [2014-04-14T01:23:42.029052 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/transport.rb:200:in `read_next_f
rame'
E, [2014-04-14T01:23:42.029077 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:63:in `run_once'
E, [2014-04-14T01:23:42.029095 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:33:in `block in r
un_loop'
E, [2014-04-14T01:23:42.029115 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:30:in `loop'
E, [2014-04-14T01:23:42.029133 #21957] ERROR -- #<Bunny::Session:69863555601680 foo@10.0.3.6:5672, vhost=/>:   /
home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bunny-1.1.9/lib/bunny/reader_loop.rb:30:in `run_loop'
2014-04-14T01:23:41Z p-21967 t-orivh26u0 ERROR: timeout
```

```
Unexpected error Connection-level error: CHANNEL_ERROR - expected 'channel.open'
```

My methodology for testing here is to queue up a thousand or more messages in RabbitMQ, then start up sneakers and see how it handles a cold start.

edit: Here's my full sneakers initializer if that's helpful:

``` ruby
require 'sneakers'
Sneakers.configure(:amqp      => ENV['AMQP_URL'],
                   :daemonize => false,
                   :prefetch  => 15,
                   :threads   => 15)
```

**Comment by drewnichols** [comment]
Did this get resolved? and if so can you share what changes you made? 

I had a similar problem where Active Record didn't seem to be releasing connections after the work() method had completed. After a bunch of googling I found that you pass the block using Active Record to ```ActiveRecord::Base.connection_pool.with_connection``` and it released the connections perfectly. 

Here's an example of how the call looks in a work method:

```ruby
def work(msg)
  id = JSON.parse(msg)['id']
  ActiveRecord::Base.connection_pool.with_connection do
    user = User.find(id)
    user.name="Homer Simpson"
    user.save
  end
  ack!
end
```

**Comment by rud** [comment]
Part of this could be an underlying Rails issue related to injected timeout exceptions on the handling thread: https://github.com/rails/rails/issues/1627 

Could this be related to long-running jobs being aborted due to timeouts and the connections not properly closed? I think at this point you pretty much have to abandon a worker-thread and setup a fresh one once a random exception is raised on it.

**Comment by drewnichols** [comment]
I've run a number of tests which triggered Active Record exceptions thrown from within the ```ActiveRecord::Base.connection_pool.with_connection do ... end``` and the workers recovered fine and continued processing subsequent messages.

**Comment by rastkojokic** [comment]
@drewnichols 
```
ActiveRecord::Base.connection_pool.with_connection
```

Fixed the problem for me

**Comment by pierre-pretorius** [comment]
You can set config in a Rails initializer as [described here](https://github.com/jondot/sneakers/pull/132) that established a new connection for each worker group similar to what heroku recommends for sidekiq:
```Ruby
Sidekiq.configure_server do |config|
  Sneakers.configure after_fork: Proc.new { ActiveRecord::Base.establish_connection }
end
```

**Comment by marothstein** [comment]
In our setup, I've seen `ActiveRecord::Base.connection_pool.with_connection` throw an exception if the database connection pool is already exhausted. 

Has anyone encountered this?

**Comment by michaelklishin** [comment]
@marothstein how is that specific to Sneakers? Connection pools have limited capacity. Sometimes the right thing to do is to increase it, sometimes it's using more application instances.

**Comment by MattSmithASU** [comment]
is there a concern of reaching the max db connection limit if each worker group has its own connection pool?

**Comment by silva96** [comment]
In rails 5 you should use 
```
Rails.application.executor.wrap do
  # your AR code
end
```
see rails/rails#26956
