### ISSUE TITLE
Getting this error while trying to drive watir within my workers

### ISSUE THREAD

**Issue by 34code** [jondot/sneakers#454]
``` ERROR: [Exception error="can't modify string; temporarily locked" error_class=RuntimeError worker_class=HardWorker]```

and the webdriver instances keep running.. 

``` backtrace=<internal:io>:63:in `read_nonblock',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/protocol.rb:210:in `rbuf_fill',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/protocol.rb:201:in `readline',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:1519:in `catch',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:1492:in `request',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/instrumentation/net_http/prepend.rb:15:in `block in request',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:26:in `block (2 levels) in request_with_tracing',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:25:in `block in request_with_tracing',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-7.1.0/lib/new_relic/agent.rb:501:in `disable_all_tracing',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:24:in `request_with_tracing',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-7.1.0/lib/new_relic/agent/instrumentation/net_http/prepend.rb:15:in `request',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:129:in `response_for',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:82:in `request',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/http_client.rb:14:in `request',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:471:in `element_tag_name',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/element.rb:88:in `tag_name',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:86:in `fetch_value',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:112:in `validate_tag',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:60:in `block in elements_match?',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:58:in `each',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:58:in `all?',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:58:in `elements_match?',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:53:in `block in matching_elements',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:53:in `select',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:53:in `matching_elements',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/matcher.rb:16:in `match',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/locator.rb:44:in `matching_elements',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/locators/element/locator.rb:29:in `locate_all',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/element_collection.rb:205:in `locate_all',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/element_collection.rb:174:in `elements',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/element_collection.rb:179:in `elements_with_tags',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/element_collection.rb:103:in `to_a',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/watir-6.19.1/lib/watir/element_collection.rb:35:in `each',/Users/sambit/Documents/RAILS/staging/botflip/sneaker_jobs/camel/camel_fetcher.rb:24:in `work',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/sneakers-2.12.0/lib/sneakers/worker.rb:65:in `block (2 levels) in process_work',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/sneakers-2.12.0/lib/sneakers/worker.rb:73:in `block in process_work',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/sneakers-2.12.0/lib/sneakers/metrics/null_metrics.rb:8:in `timing',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/sneakers-2.12.0/lib/sneakers/worker.rb:58:in `process_work',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/sneakers-2.12.0/lib/sneakers/worker.rb:48:in `block in do_work',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task',/Users/sambit/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker```

**Comment by 34code** [comment]
Also getting some of these in the sneakers output from running:
`sneakers work CamelFetcher --require sneaker_jobs/boot.rb`
-----
```#<IOError: stream closed in another thread>
#<IOError: stream closed in another thread>```

**Comment by knightq** [comment]
Same problem here:

- Rails 7.0.8.1
- Ruby 3.1.5p252 (2024-04-23 revision 1945f8dc0e) [x86_64-darwin23]
- RubyGems version 3.3.27
- Rack version 2.2.9
