### ISSUE TITLE
Intermittent spec failures

### ISSUE THREAD

**Issue by norman** [jondot/sneakers#55]
When running the Sneakers spec suite, I get random spec failures every 5 or 6 times I it. Here's a sample:

```
Finished in 1.378827s, 36.2627 runs/s, 34.0869 assertions/s.

  1) Failure:
Sneakers::Worker::#initialize::builds an internal queue#test_0001_should build a queue with correct configuration given defaults [/Users/norman/work/flexminder/sneakers/spec/sneakers/worker_spec.rb:170]:
--- expected
+++ actual
@@ -1 +1 @@
-{:runner_config_file=>nil, :metrics=>nil, :daemonize=>true, :start_worker_delay=>0.2, :workers=>4, :log=>"sneakers.log", :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>10, :threads=>10, :durable=>true, :ack=>true, :amqp=>"amqp://guest:guest@localhost:5672", :vhost=>"/", :exchange=>"sneakers", :exchange_type=>:direct, :hooks=>{}, :handler=>Sneakers::Handlers::Oneshot, :heartbeat=>2}
+{:runner_config_file=>nil, :metrics=>nil, :daemonize=>true, :start_worker_delay=>0.2, :workers=>4, :log=>"sneakers.log", :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>10, :threads=>10, :durable=>false, :ack=>true, :heartbeat=>1, :amqp=>"amqp://someuser:somepassword@somehost:5672", :vhost=>"/", :exchange=>"another_exchange", :exchange_type=>:topic, :hooks=>{}, :handler=>Sneakers::Handlers::Oneshot}



  2) Failure:
Sneakers::Worker::#initialize::builds an internal queue#test_0002_should build a queue with given configuration [/Users/norman/work/flexminder/sneakers/spec/sneakers/worker_spec.rb:177]:
--- expected
+++ actual
@@ -1 +1 @@
-{:runner_config_file=>nil, :metrics=>nil, :daemonize=>true, :start_worker_delay=>0.2, :workers=>4, :log=>"sneakers.log", :pid_path=>"sneakers.pid", :timeout_job_after=>1, :prefetch=>40, :threads=>50, :durable=>false, :ack=>false, :amqp=>"amqp://guest:guest@localhost:5672", :vhost=>"/", :exchange=>"dummy", :exchange_type=>:direct, :hooks=>{}, :handler=>Sneakers::Handlers::Oneshot, :heartbeat=>5}
+{:runner_config_file=>nil, :metrics=>nil, :daemonize=>true, :start_worker_delay=>0.2, :workers=>4, :log=>"sneakers.log", :pid_path=>"sneakers.pid", :timeout_job_after=>1, :prefetch=>40, :threads=>50, :durable=>false, :ack=>false, :heartbeat=>5, :amqp=>"amqp://someuser:somepassword@somehost:5672", :vhost=>"/", :exchange=>"dummy", :exchange_type=>:topic, :hooks=>{}, :handler=>Sneakers::Handlers::Oneshot}


50 runs, 47 assertions, 2 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /Users/norman/work/flexminder/sneakers/coverage. 711 / 780 LOC (91.15%) covered.
rake aborted!
Command failed with status (1): [ruby -I"lib:spec" -I"/Users/norman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib" "/Users/norman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "spec/sneakers/cli_spec.rb" "spec/sneakers/concerns/logging_spec.rb" "spec/sneakers/concerns/metrics_spec.rb" "spec/sneakers/publisher_spec.rb" "spec/sneakers/queue_spec.rb" "spec/sneakers/sneakers_spec.rb" "spec/sneakers/support/utils_spec.rb" "spec/sneakers/worker_spec.rb" ]
```

I'll look into it further on my end but I wanted to log the issue to track it in case anybody else is seeing it.

**Comment by rud** [comment]
Replicated:
```
$ SEED=38452 rake
Run options: --seed 38452

# Running:

EEE..............................................................................

Finished in 1.710113s, 47.3653 runs/s, 46.1958 assertions/s.

  1) Error:
Sneakers::Publisher::#publish#test_0001_should publish a message to an exchange:
NoMethodError: undefined method `info' for nil:NilClass
    ../sneakers/lib/sneakers/publisher.rb:14:in `publish'
    ../sneakers/spec/sneakers/publisher_spec.rb:14:in `block (3 levels) in <top (required)>'

Failure:
Sneakers::Publisher::#publish#test_0001_should publish a message to an exchange:
publish("test msg", {:routing_key=>"downloads"})
Called 0 times.
Expected 1 times.


  2) Error:
Sneakers::Publisher::#publish#test_0002_should publish with the persistence specified:
NoMethodError: undefined method `info' for nil:NilClass
    ../sneakers/lib/sneakers/publisher.rb:14:in `publish'
    ../sneakers/spec/sneakers/publisher_spec.rb:25:in `block (3 levels) in <top (required)>'

Failure:
Sneakers::Publisher::#publish#test_0002_should publish with the persistence specified:
publish("test msg", {:routing_key=>"downloads", :persistence=>true})
Called 0 times.
Expected 1 times.


  3) Error:
Sneakers::Publisher::#publish#test_0003_should publish with arbitrary metadata specified:
NoMethodError: undefined method `info' for nil:NilClass
    ../sneakers/lib/sneakers/publisher.rb:14:in `publish'
    ../sneakers/spec/sneakers/publisher_spec.rb:36:in `block (3 levels) in <top (required)>'
```

**Comment by rud** [comment]
Somewhat related: would a PR adding Travis CI support to the project be welcome?

**Comment by michaelklishin** [comment]
@rud that's an excellent idea.

**Comment by rud** [comment]
Reproduced on Travis:
```sh
SEED=34780 rake
Sneakers::Worker::#initialize::builds an internal queue#test_0001_should build a queue with correct configuration given defaults [/Users/rud/Projects/furious panda/sneakers/spec/sneakers/worker_spec.rb:162]:
--- expected
+++ actual
@@ -1 +1 @@
-{:runner_config_file=>nil, :metrics=>nil, :daemonize=>true, :start_worker_delay=>0.2, :workers=>4, :log=>"sneakers.log", :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>10, :threads=>10, :durable=>true, :ack=>true, :amqp=>"amqp://guest:guest@localhost:5672", :vhost=>"/", :exchange=>"sneakers", :exchange_type=>:direct, :hooks=>{}, :handler=>Sneakers::Handlers::Oneshot, :heartbeat=>2}
+{:runner_config_file=>nil, :metrics=>nil, :daemonize=>true, :start_worker_delay=>0.2, :workers=>4, :log=>"sneakers.log", :pid_path=>"sneakers.pid", :timeout_job_after=>5, :prefetch=>10, :threads=>10, :durable=>false, :ack=>true, :heartbeat=>1, :exchange=>"another_exchange", :exchange_type=>:topic, :hooks=>{}, :amqp=>"amqp://someuser:somepassword@somehost:5672", :vhost=>"/", :handler=>Sneakers::Handlers::Oneshot}
```

**Comment by rud** [comment]
I believe this issue is now fixed.

**Comment by jondot** [comment]
Thanks @rud ! :)
