### ISSUE TITLE
Cannot excute foreman start

### ISSUE THREAD

**Issue by linjunzhu** [jondot/sneakers#90]
When i follow the pos of " How to: running a stand alone worker "

And i excute ' foreman start'  then got errors: 

```ruby
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/foreman-0.77.0/lib/foreman/process.rb:54:in `spawn': Permission denied - bin/myworker (Errno::EACCES)
	from /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/foreman-0.77.0/lib/foreman/process.rb:54:in `block in run'
	from /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/foreman-0.77.0/lib/foreman/process.rb:53:in `chdir'
```

So I excute ' sudo foreman start' then got errors: 

```ruby
Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'foreman' (>= 0) among 13 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/fancy/.gem/ruby/2.0.0:/Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0', execute `gem env` for more information
	from /Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb:324:in `to_spec'
	from /Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'
	from /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/bin/foreman:22:in `<main>'
	from /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by linjunzhu** [comment]
I am on Mac OS X 10.9.5

**Comment by jondot** [comment]
Hi, please verify that bin/myworker is runnable (`chmod +x bin/myworker`).
The reason `sudo` isn't working, probably because your sudoer user doesn't have Foreman installed.

**Comment by linjunzhu** [comment]
@jondot  Thx, you are right.

However i have a new question now

```ruby
 $ foreman start
18:24:44 myworker.1 | started with pid 91607
18:24:44 myworker.1 | bin/myworker:13:in `<main>': uninitialized constant Sneakers::Metrics (NameError)
18:24:44 myworker.1 | exited with code 1
18:24:44 system     | sending SIGTERM to all processes
```

Can U help me please ? :)

**Comment by linjunzhu** [comment]
@jondot 

Here's my 'myworker' file's content

```ruby
#!/usr/bin/env ruby
require 'bundler/setup'
root = File.expand_path('../lib',File.dirname(__FILE__))
$: << root
require 'myworker'
require 'sneakers/runner'
require 'logger'
require 'statsd-ruby'


statsd = Statsd.new('localhost', 9125)

Sneakers.configure( :daemonize => false, :log => STDOUT, :metrics => Sneakers::Metrics::StatsdMetrics.new(statsd))
Sneakers.logger.level = Logger::INFO

r = Sneakers::Runner.new([ Myworker ])
r.run
```

**Comment by linjunzhu** [comment]
@jondot Hi, i am back.

Here is my new question and i have tried many time...

Can U help me ? Thx

The code:

```ruby
#!/usr/bin/env ruby
require 'bundler/setup'
root = File.expand_path('../lib',File.dirname(__FILE__))
$: << root
require 'myworker'
require 'sneakers/runner'
require 'logger'
require 'statsd-ruby'


statsd = Statsd.new(ENV['STATSD_HOST'], 9125)

Sneakers.configure( :amqp => ENV['AMQP_URL'], :daemonize => false, :log => STDOUT, :metrics => Sneakers::Metrics::StatsdMetrics.new(statsd))
Sneakers.logger.level = Logger::INFO

r = Sneakers::Runner.new([ Myworker ])
r.run
```

And got errors: 

```ruby
 $ foreman start
20:27:20 myworker.1 | started with pid 9883
20:27:20 myworker.1 | bin/myworker:13:in `<main>': uninitialized constant Sneakers::Metrics (NameError)
20:27:20 myworker.1 | exited with code 1
20:27:20 system     | sending SIGTERM to all processes
```

**Comment by jondot** [comment]
Sure, try `require 'sneakers/metrics/statsd_metrics'`

**Comment by linjunzhu** [comment]
@jonot yeah, i require it  and next step got errors:
```ruby
 $ foreman start
11:28:32 myworker.1 | started with pid 8447
11:28:33 myworker.1 | /Users/fancy/ruby_projects/myworker/lib/myworker.rb:3:in `<top (required)>': Myworker is not a class (TypeError)
11:28:33 myworker.1 | 	from bin/myworker:5:in `require'
11:28:33 myworker.1 | 	from bin/myworker:5:in `<main>'
11:28:33 myworker.1 | exited with code 1
11:28:33 system     | sending SIGTERM to all processes
```

So i `require 'sneakers'` and got new errors :
```ruby
unner.rb:12:in `run'
11:29:36 myworker.1 |   bin/myworker:19:in `<main>'
11:29:36 myworker.1 | Unexpected error undefined method `new' for Myworker:Module
11:29:36 myworker.1 |   /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/workergroup.rb:22:in `block in run'
11:29:36 myworker.1 |   /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/workergroup.rb:22:in `map'
11:29:36 myworker.1 |   /Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/workergroup.rb:22:in `run'
```

Here is `myworker.rb` :
```ruby
require "myworker/version"

module Myworker
  # Your code goes here...
end

```



Now i just want to add a worker like this :

```ruby
class MyWorker
  include Sneakers::Worker
  from_queue 'dashboard.posts'

  def work(msg)
    logger.info "hello #{msg}"
    manual_ack!
  end
end
```

What should i do please ?
